import bs4, lxml, time, re, Utilities, json, tqdm, sqlite3, urllib.parse

categoriesRegex: re.Pattern = re.compile(r'\[\[Category:(.+)\]\]', re.IGNORECASE)
disallowedCategories: set[str] = set([
	"Commercial links", 
	"Universes", 
	"Summary links", 
	"Direct links", 
	"Disambiguation pages",
	"Mascot links",
	"Crossover rules",
	"Undirect links",
	"Commercials"
])

def inDisallowedCategory(p: bs4.element.Tag) -> bool:
	articleText: str = p.revision.find("text").get_text() # type: ignore
	matches: list[str] = re.findall(categoriesRegex, articleText)

	return not disallowedCategories.isdisjoint(set(matches))

def convertToTSArray() -> None:
	with open("text/filtered_franchises.txt", "r", encoding="utf-8") as file:
		franchises: list[str] = [f.strip().replace('"', '\\"') for f in file.readlines()]

	with open("web/src/assets/filtered_franchises.ts", "w", encoding="utf-8") as file:
		file.write("//autogenerated via python script\n")
		file.write("//just copying over the file requires making a network request + splitting it and making an array, which takes too long\n")
		file.write("export const franchiseList: string[] = [\n")
		for f in franchises:
			file.write(f'\t"{f}",\n')
		file.write("];")

def extractTable(page: bs4.element.Tag, title: str) -> str|None:
	content: str = page.revision.find("text").get_text() # type: ignore
	try:
		table: str = re.split(r'== ?Links? to other.+==', content, flags=re.IGNORECASE)[1] #some articles have "Link to other series" instead of "links"
	except:
		return None
	return table


if __name__ == "__main__":
	with open("text/fictionalcrossover_pages_current.xml", "r", encoding="UTF-8") as file:
		content = ''.join(file.readlines())

	# note to self: it takes ~8 seconds to create the bs4 object. i tried
	# dumping it to disk after creating it and reading the pkl file whenever i run the script
	# it still takes 8 seconds to read it from disk
	soup: bs4.BeautifulSoup = bs4.BeautifulSoup(content, "lxml")
	pages: list = sorted([p for p in soup.find_all("page") if p.ns and p.ns.text.strip() == '0'], key=lambda p: p.title.contents[0]) # type: ignore # all articles are in namespace 0

	# note: redirects can furtuerh redirect
	# eg     "Archie": "Archie (Comic Series)" and "Archie (Comic Series)": "Archie (Archie Comics)",
	# or Minna to Series -> Minna to (Series) -> Minna to
	# need to fix


	print("Begining parse")
	knownRedirects : dict[str, str] = Utilities.getRedirects()
	miscRemovals   : set[str] = Utilities.getRemovals()
	redirects: dict[str, str] = {}
	removalsWasUpdated : bool = False
	franchises: list[str] = []
	franchiseToPage: dict[str, str] = {}

	failures = []
	for p in tqdm.tqdm(pages):
		title: str = Utilities.sanitize(p.title.contents[0])
		if p.redirect:
			destination: str = Utilities.sanitize(p.redirect.get("title")).strip()
			redirects[title] = destination
			continue

		# not all articles are categorized correctly
		if title in miscRemovals or inDisallowedCategory(p):
			continue
		

		table: str|None = extractTable(p, title)
		if not table: 
			failures.append(title)
			continue

		franchiseToPage[title] = table
		franchises.append(title)

	# Utilities.writeToFile("text/failures.txt", failures)
	Utilities.writeToFile("text/filtered_franchises.txt", franchises)
	Utilities.writeToJSON("text/redirects.json", redirects)
	convertToTSArray()

	with open("text/test.json", "w", encoding="utf-8") as file:
		json.dump(franchiseToPage, file, indent=4)

	conn: sqlite3.Connection = sqlite3.connect('text/crossovers.db')
	cursor: sqlite3.Cursor = conn.cursor()
	query: str = "INSERT INTO game (name, url) VALUES (?, ?)"

	with open('text/filtered_franchises.txt', 'r', encoding='utf-8') as file:
		for line in file.readlines():
			url: str = Utilities.URL_BASE + urllib.parse.quote(line)
			
			cursor.execute(query, (line.strip(), url))
	
	conn.commit()
	conn.close()

		
